---
- name: delete index.html-1
  file:
    path: "{{ dest_index_del1 }}" 
    state: absent
  ignore_errors: yes

- name: delete index.html-2
  file:
    path: "{{ dest_index_del2 }}" 
    state: absent
  ignore_errors: yes

- name: template index.php
  template:
    src: index.php.j2
    dest: "{{ dest_index_file }}"
    mode: "666"
  notify:
    - restart httpd
